- hosts: myserver
  vars: 
    - image: backend3ais/web-apache
  tasks:
    - name: Install python-docker di ubuntu
      apt:
        name: "{{ item }}"
      loop: 
        - python3
        - python3-docker
      when: ansible_distribution == "Ubuntu"

    - name: pull image docker
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes

    - name: run container
      docker_container:
        name: web_server
        image: "{{ image }}"
        state: started
        published_ports:
        - 10000:80
        recreate: yes
